//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.Rating = 1;
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ReviewDetails { get; set; }
        public string ReviewerName { get; set; }
        public int Rating { get; set; }
        public string ReviewLocation { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int MediaId { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual User User { get; set; }
    }
}
